"""add_billable_expenses_fields

Revision ID: 3db3aa2ad8d2
Revises: 996b16c37f96
Create Date: 2026-04-02 23:37:26.550512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db3aa2ad8d2'
down_revision: Union[str, None] = '996b16c37f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_billable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('expenses', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'client_id')
    op.drop_column('expenses', 'is_billable')
    # ### end Alembic commands ###
