"""add_amount_paid_balance_due

Revision ID: 996b16c37f96
Revises: a53290a5f4b6
Create Date: 2026-04-02 22:19:11.600525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996b16c37f96'
down_revision: Union[str, None] = 'a53290a5f4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
    op.add_column('invoices', sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
    # Set balance_due = total for existing invoices that aren't paid
    op.execute("UPDATE invoices SET balance_due = total WHERE status != 'PAID'")
    op.execute("UPDATE invoices SET amount_paid = total, balance_due = 0 WHERE status = 'PAID'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance_due')
    op.drop_column('invoices', 'amount_paid')
    # ### end Alembic commands ###
