"""add_items_catalog_client_invoice_settings_year_flag

Revision ID: ac5cf42db362
Revises: eec0ae411fe1
Create Date: 2026-04-01 12:20:34.170395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5cf42db362'
down_revision: Union[str, None] = 'eec0ae411fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.add_column('clients', sa.Column('invoice_prefix', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('next_invoice_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('clients', sa.Column('use_year_in_number', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('clients', sa.Column('default_payment_terms_days', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('default_notes', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('bank_account_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('bank_sort_code', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('bank_iban', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('bank_swift', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('use_year_in_number', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'use_year_in_number')
    op.drop_column('clients', 'bank_swift')
    op.drop_column('clients', 'bank_iban')
    op.drop_column('clients', 'bank_sort_code')
    op.drop_column('clients', 'bank_account_number')
    op.drop_column('clients', 'bank_account_name')
    op.drop_column('clients', 'bank_name')
    op.drop_column('clients', 'default_notes')
    op.drop_column('clients', 'default_payment_terms_days')
    op.drop_column('clients', 'use_year_in_number')
    op.drop_column('clients', 'next_invoice_number')
    op.drop_column('clients', 'invoice_prefix')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
